In [2]:
include("./helpers.jl")

Main.Helpers

In [4]:
module Task_1
using ..Main.Helpers
# Варіант 5
A = Helpers.A
create_realtions(A, A) |> display
R1 = create_realtions(A, A, colder_eq)
display(R1)
plot_graph(R1, A)
end

4×4 Matrix{Tuple{Char, Char}}:
 ('В', 'В')  ('В', 'З')  ('В', 'Л')  ('В', 'О')
 ('З', 'В')  ('З', 'З')  ('З', 'Л')  ('З', 'О')
 ('Л', 'В')  ('Л', 'З')  ('Л', 'Л')  ('Л', 'О')
 ('О', 'В')  ('О', 'З')  ('О', 'Л')  ('О', 'О')

4×4 Matrix{Bool}:
 1  0  1  0
 1  1  1  1
 0  0  1  0
 1  0  1  1

LoadError: UndefVarError: plot_graph not defined

In [57]:
module Task_3
using ..Main.Helpers
using LinearAlgebra

consistency_check(R1::Matrix{Bool}, R2::Matrix{Bool}) = @assert size(R1) == size(R2) "size(R1) must equal size(R2)" 

"""
R1 = Bool[1 1 1 1; 0 1 1 1; 0 1 0 0; 1 0 1 0]
R2 = Bool[0 1 0 1; 0 0 0 1; 0 1 0 0; 0 0 1 0]
r_mult(R1, R2) |> display

4×4 Matrix{Bool}:
 0  1  1  1
 0  1  1  1
 0  0  0  1
 0  1  0  1
"""
function matrix_op(relation)
    return function r_union(R1::Matrix, R2::Matrix)
        consistency_check(R1, R2)
        new_R = copy(R1)
        map(arg -> relation(R2[arg[1]], arg[2]), enumerate(new_R))
    end
end

# добуток/композиція
function r_mult(R1::Matrix{Bool}, R2::Matrix{Bool})
    consistency_check(R1, R2)
    r, c = size(R1)
    R_new = zeros(Bool, r, c)
    for i in 1:r, j in 1:c
        R_new[i, j] = any(R1[i, :] .& R2[:, j])
    end
    R_new
end
    
# об'єднання
r_union = matrix_op(|)
# перетин
r_intersec = matrix_op(&)
# обернене
r_rotated(R::Matrix) = transpose(R)
# доповнення
r_inverse(R::Matrix) = map(!, R)

# Execution
A = Helpers.A
println("Set A: ", A)
R = create_realtions(A, A, colder_eq)
println("R: ", R)

println("Inverse: ", r_inverse(R))
println("Union: ", r_union(R, R))
println("Intersection: ", r_intersec(R, R))
println("Rotation: ", r_rotated(R))
println("Compositon: ", r_mult(R, R))

end

Set A: ['В', 'З', 'Л', 'О']
R: Bool[1 0 1 0; 1 1 1 1; 0 0 1 0; 1 0 1 1]
Inverse: Bool[0 1 0 1; 0 0 0 0; 1 1 0 1; 0 1 0 0]
Union: 

Bool[1 0 1 0; 1 1 1 1; 0 0 1 0; 1 0 1 1]
Intersection: Bool[1 0 1 0; 1 1 1 1; 0 0 1 0; 1 0 1 1]
Rotation: Bool[1 1 0 1; 0 1 0 0; 1 1 1 1; 0 1 0 1]
Compositon: Bool[1 0 1 0; 1 1 1 1; 0 0 1 0; 1 0 1 1]


Main.Task_3