In [88]:
include("./helpers.jl")

module Task_6
using ..Main.Helpers
using LinearAlgebra

# Варіант 5
R1 =  Bool[
    1 1 0 0 0; 
    0 0 0 1 0;
    1 1 0 1 0; 
    0 0 0 1 0;
    0 0 0 1 0]

function min(R)
    counts = []
    len = size(R)[1]
    for i in 1:len
        push!(counts, sum(R[:, i]))
    end
    maxval, idx = findmax(counts)
    nums =  [idx]
    for i in 1:len
        if counts[i] == maxval && i != nums[1]
            push!(nums, i)
        end 
    end
    return R[:, nums], nums
end

indifference(R) = r_intersec(R, r_rotated(R))
dominance(R) = r_intersec(R, r_inverse(indifference(R)))
# Відношення непорівняльності
notequal(R) = r_union(r_union(dominance(R), indifference(R)), 
                      r_rotated(dominance(R)))
    

max(R) = min(transpose(R))
minoranta(R) = max(r_inverse(R))
majoranta(R) = min(r_inverse(R))

R1_min, mins = min(R1)
R1_max, maxs = max(R1)
println("Minimum: ", mins)
println("Maximum: ", maxs)

R1_mino, i = minoranta(R1)
R1_majo, j = majoranta(R1)

println("Minoranta: ", i)
println("Majoranta: ", j)

display(R1)
display(indifference(R1))
display(dominance(R1))
display(notequal(R1))

end

5×5 Matrix{Bool}:
 1  1  0  0  0
 0  0  0  1  0
 1  1  0  1  0
 0  0  0  1  0
 0  0  0  1  0

5×5 Matrix{Bool}:
 1  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  1  0
 0  0  0  0  0

5×5 Matrix{Bool}:
 0  1  0  0  0
 0  0  0  1  0
 1  1  0  1  0
 0  0  0  0  0
 0  0  0  1  0

5×5 Matrix{Bool}:
 1  1  1  0  0
 1  0  1  1  0
 1  1  0  1  0
 0  1  1  1  1
 0  0  0  1  0

Minimum: [4]
Maximum: [3]
Minoranta: [2, 4, 5]
Majoranta: [3, 5]


Main.Task_6

In [47]:
?findmax

search: findmax findmax! findmin findmin!



```
findmax(itr) -> (x, index)
```

Return the maximum element of the collection `itr` and its index or key. If there are multiple maximal elements, then the first one will be returned. If any data element is `NaN`, this element is returned. The result is in line with `max`.

The collection must not be empty.

# Examples

```jldoctest
julia> findmax([8,0.1,-9,pi])
(8.0, 1)

julia> findmax([1,7,7,6])
(7, 2)

julia> findmax([1,7,7,NaN])
(NaN, 4)
```

---

```
findmax(A; dims) -> (maxval, index)
```

For an array input, returns the value and index of the maximum over the given dimensions. `NaN` is treated as greater than all other values.

# Examples

```jldoctest
julia> A = [1.0 2; 3 4]
2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

julia> findmax(A, dims=1)
([3.0 4.0], CartesianIndex{2}[CartesianIndex(2, 1) CartesianIndex(2, 2)])

julia> findmax(A, dims=2)
([2.0; 4.0], CartesianIndex{2}[CartesianIndex(1, 2); CartesianIndex(2, 2)])
```
